---
platform: linux

input:
  - name: source

output:
  - name: tfplan

params:
  TF_IN_AUTOMATION: 1

run:
  dir: source
  path: sh
  args:
    - -c
    - |
      set -euo pipefail
      echo "Running Terraform workspace create for -$(cat .git/resource/head_sha | head -c 8)"

      terraform init -input=false
      terraform workspace new ${TARGET_ENVIRONMENT}-$(cat .git/resource/head_sha | head -c 8)
