---
platform: linux

inputs:
  - name: source
    path: .
  - name: .terraform 

outputs:
  - name: .terraform

params:
  TF_IN_AUTOMATION: 1
  WORKSPACE_PREFIX: homelab

  KUBE_HOST: ((vault:kv/kubernetes.host))
  KUBE_CLUSTER_CA_CERT_DATA: ((vault:kv/kubernetes.cluster_ca_certificate))
  KUBE_CLIENT_CERT_DATA: ((vault:kv/kubernetes.client_certificate))
  KUBE_CLIENT_KEY_DATA: ((vault:kv/kubernetes.client_key))

run:
  path: sh 
  args:
    - -c 
    - |
      set -euo pipefail
      exec terraform workspace new ${WORKSPACE_PREFIX}-$(cat .git/resource/head_sha | head -c 8)
