---
groups:
  - name: pull-requests
    jobs:
      - deploy-pr

var_sources:
- name: vault
  type: vault
  config:
    url: http://vault.vault.svc
    path_prefix: /concourse
    client_token: ((auth-token))

- name: azure
  type: dummy
  config:
    vars:
      master_app: ((vault:azure/creds/master_app))

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: pull-request
  type: pull-request
  icon: github
  source:
    repository: secureweb/homelab
    access_token: ((vault:kv/github))

- name: terraform
  type: registry-image
  source:
    repository: hashicorp/terraform
    tag: 0.13.0-beta3

- name: openpolicyagent
  type: registry-image
  source:
    repository: openpolicyagent/opa

jobs:
- name: deploy-pr
  plan:
  - in_parallel:
    - get: pull-request
      trigger: true
    - get: terraform
    - get: openpolicyagent
  - task: terraform init
    file: pull-request/ci/tasks/terraform-init.yml
    image: terraform
    input_mapping:
      source: pull-request
    output_mapping:
      .terraform: terraform_init
  - task: terraform workspace new
    file: pull-request/ci/tasks/terraform-workspace-new.yml
    image: terraform
    input_mapping: 
      source: pull-request
      .terraform: terraform_init
    output_mapping:
      .terraform: terraform_workspace
  - task: terraform plan
    file: pull-request/ci/tasks/terraform-plan.yml
    image: terraform
    input_mapping:
      source: pull-request
      .terraform: terraform_workspace
    params: 
      ARM_TENANT_ID: ((vault:kv/azure.tenant_id))
      ARM_SUBSCRIPTION_ID: ((vault:kv/azure.tenant_id)) # subscription = tenant = no-subscription.
      ARM_CLIENT_ID: ((azure:master_app.client_id))
      ARM_CLIENT_SECRET: ((azure:master_app.client_secret))
  - task: terraform apply
    file: pull-request/ci/tasks/terraform-plan.yml
    image: terraform
    input_mapping:
      source: pull-request
      .terraform: terraform_workspace
    params:
      ARM_TENANT_ID: ((vault:kv/azure.tenant_id))
      ARM_SUBSCRIPTION_ID: ((vault:kv/azure.tenant_id)) # subscription = tenant = no-subscription.
      ARM_CLIENT_ID: ((azure:master_app.client_id))
      ARM_CLIENT_SECRET: ((azure:master_app.client_secret))
  ensure:
    do:
    - try:
        task: terraform destroy
        file: pull-request/ci/tasks/terraform-destroy.yml
        image: terraform
        input_mapping:
          source: pull-request
          .terraform: terraform_workspace
    - task: terraform workspace delete
      file: pull-request/ci/tasks/terraform-workspace-delete.yml
      image: terraform
      input_mapping:
        source: pull-request
        .terraform: terraform_init
